apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deploy
  namespace: myspace
  labels:
    name: app-deploy

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: myapp-pod
  template:
    metadata:
      name: myapp-pod
      namespace: myspace
      labels:
        name: myapp-pod
    spec:
      containers:
      - name: mypp-container
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mydb-svc.myspace.svc.cluster.local 
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"